begin;
insert into public.topic_clusters (
  id, topic, subtopic, paper_types, band_min, band_max,
  word_goal, candidate_goal, chinese_learner_priority,
  curriculum_version, human_review
)
values
  ('daily_life_people_and_family','Daily Life','people and family','{"General"}'::text[],4.0,4.0,160,280,'high',1,false),
  ('daily_life_home_and_objects','Daily Life','home and objects','{"General"}'::text[],4.0,4.0,160,280,'high',1,false),
  ('daily_life_food_and_drink','Daily Life','food and drink','{"General"}'::text[],4.0,4.0,160,280,'high',1,false),
  ('daily_life_time_and_numbers','Daily Life','time and numbers','{"General"}'::text[],4.0,4.0,140,240,'high',1,false),
  ('daily_life_basic_actions_and_verbs','Daily Life','basic actions and verbs','{"General"}'::text[],4.0,4.0,180,320,'high',1,false),
  ('daily_life_colours_shapes_and_descriptions','Daily Life','colours shapes and descriptions','{"General"}'::text[],4.0,4.0,140,240,'medium',1,false),
  ('daily_life_feelings_and_emotions','Daily Life','feelings and emotions','{"Speaking"}'::text[],4.0,4.0,140,240,'high',1,false),
  ('daily_life_school_and_study_basics','Daily Life','school and study basics','{"General"}'::text[],4.0,4.0,140,240,'high',1,false),
  ('daily_life_travel_and_places','Daily Life','travel and places','{"Speaking","Listening"}'::text[],4.0,4.0,160,280,'high',1,false),
  ('daily_life_shopping_and_money_basics','Daily Life','shopping and money basics','{"Listening","Speaking"}'::text[],4.0,4.0,120,220,'medium',1,false),
  ('daily_life_body_and_health_basics','Daily Life','body and health basics','{"Speaking","Listening"}'::text[],4.0,4.0,140,240,'high',1,false),
  ('daily_life_animals_and_nature_basics','Daily Life','animals and nature basics','{"General"}'::text[],4.0,4.0,120,220,'medium',1,false),
  ('daily_life_weather_and_seasons','Daily Life','weather and seasons','{"General"}'::text[],4.0,4.0,120,220,'medium',1,false),
  ('daily_life_sports_and_leisure','Daily Life','sports and leisure','{"Speaking"}'::text[],4.0,4.0,140,240,'medium',1,false),
  ('daily_life_transport_and_getting_around','Daily Life','transport and getting around','{"Listening"}'::text[],4.0,4.0,120,220,'medium',1,false),
  ('daily_life_numbers_and_quantity','Daily Life','numbers and quantity','{"General"}'::text[],4.0,4.0,120,220,'medium',1,false),
  ('daily_life_clothes_and_appearance','Daily Life','clothes and appearance','{"Speaking"}'::text[],4.0,4.0,100,180,'low',1,false),
  ('education_school_systems_and_structure','Education','school systems and structure','{"Writing","Speaking"}'::text[],4.5,5.0,220,380,'high',1,false),
  ('education_university_and_higher_education','Education','university and higher education','{"Writing","Speaking"}'::text[],4.5,5.5,220,380,'high',1,false),
  ('education_teaching_and_learning_methods','Education','teaching and learning methods','{"Writing","Speaking"}'::text[],5.0,5.5,220,380,'high',1,false),
  ('education_exams_and_assessment','Education','exams and assessment','{"Writing","Reading"}'::text[],4.5,5.5,220,380,'high',1,false),
  ('education_online_and_technology_in_education','Education','online and technology in education','{"Writing","Speaking"}'::text[],5.5,6.0,220,380,'high',1,false),
  ('health_medical_care_and_treatment','Health','medical care and treatment','{"Reading","Listening"}'::text[],4.5,5.0,220,380,'high',1,false),
  ('health_diet_nutrition_and_lifestyle','Health','diet nutrition and lifestyle','{"Writing","Speaking"}'::text[],4.5,5.5,220,380,'high',1,false),
  ('health_mental_health_and_wellbeing','Health','mental health and wellbeing','{"Writing","Speaking"}'::text[],5.5,6.0,200,340,'medium',1,false),
  ('environment_natural_world_and_ecosystems','Environment','natural world and ecosystems','{"Reading"}'::text[],4.5,5.0,250,430,'high',1,false),
  ('environment_climate_change_and_global_warming','Environment','climate change and global warming','{"Writing","Speaking"}'::text[],5.0,6.0,300,520,'high',1,false),
  ('environment_pollution_and_waste','Environment','pollution and waste','{"Writing","Speaking"}'::text[],5.0,5.5,260,450,'high',1,false),
  ('environment_conservation_and_sustainability','Environment','conservation and sustainability','{"Writing","Reading"}'::text[],5.5,6.5,280,480,'high',1,false),
  ('technology_everyday_technology','Technology','everyday technology','{"Speaking","Listening"}'::text[],4.5,5.0,180,310,'high',1,false),
  ('technology_digital_society_and_internet','Technology','digital society and internet','{"Writing","Speaking"}'::text[],5.5,6.5,260,450,'high',1,false),
  ('technology_science_and_innovation','Technology','science and innovation','{"Reading","Writing"}'::text[],6.0,7.0,260,450,'high',1,false),
  ('technology_automation_and_future_of_work','Technology','automation and future of work','{"Writing"}'::text[],6.0,7.0,220,380,'high',1,false),
  ('work_jobs_and_career_basics','Work','jobs and career basics','{"Speaking","Listening"}'::text[],4.5,5.0,220,380,'high',1,false),
  ('work_workplace_skills_and_qualities','Work','workplace skills and qualities','{"Writing","Speaking"}'::text[],5.0,6.0,220,380,'medium',1,false),
  ('work_employment_trends','Work','employment trends','{"Writing","Reading"}'::text[],6.0,7.0,220,380,'medium',1,false),
  ('work_business_and_entrepreneurship','Work','business and entrepreneurship','{"Writing","Reading"}'::text[],6.0,7.0,200,340,'medium',1,false),
  ('society_urban_life_and_cities','Society','urban life and cities','{"Writing","Reading"}'::text[],5.5,6.5,260,450,'high',1,false),
  ('society_crime_and_law','Society','crime and law','{"Writing","Reading"}'::text[],5.5,6.5,260,450,'high',1,false),
  ('society_family_and_social_change','Society','family and social change','{"Writing","Speaking"}'::text[],5.0,6.0,220,380,'high',1,false),
  ('society_gender_equality_and_rights','Society','gender equality and rights','{"Writing","Speaking"}'::text[],6.0,7.0,220,380,'medium',1,false),
  ('media_news_and_journalism','Media','news and journalism','{"Reading","Writing"}'::text[],5.5,6.5,220,380,'high',1,false),
  ('media_advertising_and_marketing','Media','advertising and marketing','{"Writing","Reading"}'::text[],5.5,6.5,220,380,'high',1,false),
  ('media_social_media_and_communication','Media','social media and communication','{"Writing","Speaking"}'::text[],5.5,6.5,220,380,'high',1,false),
  ('government_politics_and_policy','Government','politics and policy','{"Writing","Reading"}'::text[],6.0,7.0,220,380,'medium',1,false),
  ('government_public_services_and_welfare','Government','public services and welfare','{"Writing","Reading"}'::text[],6.0,7.0,220,380,'medium',1,false),
  ('government_international_relations','Government','international relations','{"Reading","Writing"}'::text[],6.5,7.5,200,340,'medium',1,false),
  ('economy_personal_finance_and_banking','Economy','personal finance and banking','{"Listening","Reading"}'::text[],5.0,6.0,180,310,'high',1,false),
  ('economy_national_economy_and_growth','Economy','national economy and growth','{"Writing","Reading"}'::text[],6.5,7.5,240,420,'medium',1,false),
  ('economy_global_trade_and_development','Economy','global trade and development','{"Reading","Writing"}'::text[],7.0,8.0,220,380,'medium',1,false),
  ('science_biology_and_human_body','Science','biology and human body','{"Reading"}'::text[],5.5,6.5,200,340,'medium',1,false),
  ('science_physics_and_chemistry_basics','Science','physics and chemistry basics','{"Reading"}'::text[],6.0,7.0,180,310,'low',1,false),
  ('science_space_and_astronomy','Science','space and astronomy','{"Reading"}'::text[],6.5,7.5,180,310,'low',1,false),
  ('science_research_and_data','Science','research and data','{"Reading","Writing"}'::text[],6.5,8.0,260,450,'medium',1,false),
  ('academic_language_academic_verbs','Academic Language','academic verbs','{"Writing","Reading"}'::text[],6.0,8.0,220,380,'high',1,false),
  ('academic_language_academic_nouns','Academic Language','academic nouns','{"Writing","Reading"}'::text[],6.0,8.0,240,420,'high',1,false),
  ('academic_language_academic_adjectives_and_adverbs','Academic Language','academic adjectives and adverbs','{"Writing","Reading"}'::text[],6.0,8.0,220,380,'high',1,false),
  ('academic_language_cause_and_effect_language','Academic Language','cause and effect language','{"Writing"}'::text[],6.0,8.0,220,380,'high',1,false),
  ('academic_language_comparison_and_contrast_language','Academic Language','comparison and contrast language','{"Writing","Reading"}'::text[],6.0,8.0,220,380,'high',1,false),
  ('academic_language_stance_and_evaluation_language','Academic Language','stance and evaluation language','{"Writing","Speaking"}'::text[],6.5,8.0,220,380,'high',1,false),
  ('academic_language_data_and_trend_language','Academic Language','data and trend language','{"Writing"}'::text[],6.5,8.0,240,420,'high',1,false),
  ('academic_language_argument_and_counterargument_language','Academic Language','argument and counterargument language','{"Writing"}'::text[],7.0,8.0,260,450,'high',1,false)
on conflict (id) do update
set topic = excluded.topic,
    subtopic = excluded.subtopic,
    paper_types = excluded.paper_types,
    band_min = excluded.band_min,
    band_max = excluded.band_max,
    word_goal = excluded.word_goal,
    candidate_goal = excluded.candidate_goal,
    chinese_learner_priority = excluded.chinese_learner_priority,
    curriculum_version = excluded.curriculum_version,
    human_review = excluded.human_review,
    updated_at = now();
commit;
